# Generated by Django 3.1.6 on 2021-06-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('click_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(db_index=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='banner.banner')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='banner.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('conversion_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('revenue', models.DecimalField(decimal_places=8, max_digits=10)),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='banner.click')),
            ],
        ),
        migrations.AddField(
            model_name='click',
            name='impression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='banner.impression'),
        ),
    ]
