# Generated by Django 3.1.6 on 2021-06-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='click',
            unique_together={('click_id', 'impression')},
        ),
        migrations.AlterUniqueTogether(
            name='impression',
            unique_together={('quarter', 'banner', 'campaign')},
        ),
    ]
