# Generated by Django 3.1.6 on 2021-06-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20210603_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='banner.banner')),
            ],
        ),
    ]
