# Generated by Django 3.1.6 on 2021-06-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_bannerseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerseen',
            name='datetime',
        ),
    ]
