# Generated by Django 3.1.6 on 2021-06-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_remove_bannerseen_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='impression',
            unique_together=set(),
        ),
    ]
