# Generated by Django 3.1.6 on 2021-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20210604_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='impression',
        ),
        migrations.AddField(
            model_name='click',
            name='num_impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
