# Generated by Django 3.1.6 on 2021-06-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20210604_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='banner.banner'),
        ),
        migrations.AddField(
            model_name='click',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='banner.campaign'),
        ),
    ]
