# Generated by Django 3.1.6 on 2021-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_auto_20210604_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='quarter',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
    ]
