# Generated by Django 3.2.4 on 2021-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_auto_20210605_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='conversion_revenue_sum',
            field=models.DecimalField(db_index=True, decimal_places=8, default=0, max_digits=20),
        ),
    ]
